[package]
name = "Serus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "serus"
path = "src/bin/repl.rs"

[lib]
name = "lib"
path = "src/lib.rs"
